Full price estimates for all sub-assemblies and full enclosed v0.3
RespiraWorks/Ventilator pull request #1069
Opened 2021-02-27 22:28 UTC by martukas

Not much to say here.
Done manually, rounding and calc punching and all.
So could have errors potentially. Some of the decisions of what optional things to count or not were a bit arbitrary, but tried to err on the side of more expensive, since we probably will need more junk in future versions.

2021-02-28 20:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RespiraWorks/Ventilator?pullRequest=1069) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RespiraWorks/Ventilator?pullRequest=1069) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RespiraWorks/Ventilator?pullRequest=1069) it.</sub>

2021-03-01 23:00 UTC, inceptionev requested changes
looks good, a few minor comments.  bulk materials that are cut-to-size are not expressed in the same way, and this is a bit confusion.  I suspect that a subtotal column might offer a way to clear this up in a consistent way, but I am also ok punting this to a future effort.

2021-03-02 00:32 UTC, inceptionev commented
ok to merge as-is, can punt minor improvements to formatting to future work if needed

2021-03-02 00:32 UTC, inceptionev approved these changes

2021-03-02 02:19 UTC, martukas commented
Most of those problems concern accounting for consumables used in manufacture of custom parts. The  problem is now captured in #1074 and the more sustainable solution will probably be devised in #1011

2021-03-02 02:19 UTC, merged