Issue 1098 airintake cutouts
RespiraWorks/Ventilator pull request #1117
Opened 2021-05-25 16:39 UTC by gokcemay

# Description

Added grille to the bottom. 
Added new technical drawings for enclosure parts.

Fixes #1098

# General checklist:

- [ ] I have performed a self-review, including - looked through the `Files changed` tab, browsed repository in my branch
- [ ] I have made corresponding changes to the documentation - to reflect changes in code, electrical or mechanical design
- [ ] All new documentation or graphics follow the [documentation style guide](https://github.com/RespiraWorks/Ventilator/wiki/Documentation-style-guide)
- [ ] All new content is linked, easily discoverable, does not require too many clicks
- [ ] I have reviewed any other relevant parts of our [contributor wiki](https://github.com/RespiraWorks/Ventilator/wiki) to ensure that this PR conforms to the standards
- [ ] I have given the PR a descriptive name (prefixed with **WIP** if it is not yet ready for review)
- [ ] I have tagged relevant reviewers

2021-05-25 16:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RespiraWorks/Ventilator?pullRequest=1117) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RespiraWorks/Ventilator?pullRequest=1117) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RespiraWorks/Ventilator?pullRequest=1117) it.</sub>

2021-05-26 07:28 UTC, martukas requested changes
General stuff and model:
* do not see any drawings for equipment tray and the display & PCB frames
* bottom filter and long bumper files probably don't have to be here since we are not using them
* all rivets and internals-to-enclosure fasteners have been turned invisible
* big bumpers still present in model, but old bumpers are also still present, just made invisible. But it is probably correct to have bumpers be part of the bottom assembly, like it was done with the new ones, so once those are gone, it is a good idea to demote the old ones into sub-assembly
* bottom grille pattern looks cool!
* One pattern could probably be mirrored instead of making 2 separate patterns
* Might we want some mounting holes to make it possible to add filter from the inside?
* bottom plate sketch lines left visible outside the scope of that part

Drawings:
* back panel drawing has this extra line in top view. Is that supposed to be there?
![image](https://user-images.githubusercontent.com/1972005/119617840-367de680-bdd0-11eb-8d81-6a5dff0307ef.png)
* Revision history dates are not (consistently) following our intended format. Maybe we need to set the tone for this in the drawing templates?
* In front panel, do you think we should more explicitly say that one of those distances is size of cutout diagonally measured (marked in red)? Also, is it at all important what distance is from front to back (marked in blue)? I did not see this noted in top view. 
![image](https://user-images.githubusercontent.com/1972005/119619072-9e80fc80-bdd1-11eb-89d9-647a45df91aa.png)
* Side view looks good, but may have to be updated when we merge Meg's changes
* I see there is a drawing for the left reflection of the side panel, but it is probably not necessary? We can just tell manufacturer "mirror this"? At least the ones in Califonia were totally fine with that.

As an additional note, once we finalize the drawings, we should probably also add PDF exports to the repository. But we can probably do this in a future PR when things are more "finalized", or at least when we end up sending drawings to manufacturer. We should permanently save whatever version ends up being used.

2021-08-25 07:14 UTC, gokcemay commented
* The dashed line is the thickness of the steel, viewed from top. 
* The 129mm is panel opening viewed from normal angle.

2021-08-31 17:08 UTC, martukas approved these changes
Looks good now

2021-08-31 17:10 UTC, merged