Adds high level functions to debugging interface
RespiraWorks/Ventilator pull request #1290
Opened 2022-07-20 05:05 UTC by a-vinod

# Description

This adds some new functionality to the `set var` command in the debugging interface. Namely

1. High level functions to generate floatarray values

**Linear function**: `set var psol_cal lin(a,b)` sets floatarray to evenly spaced values from a to b
**Identity function**:  `set var psol_cal eigen()` sets floatarray to evenly spaced values from 0 to 1 (wrapper for `lin(0,1)`)

2. Passing raw string as input

`set var "somestring"`

Not tested as none of the settable debug variables are strings yet

Updates #1273 

## Self-review checklist:

- [x] Self-review: looked through the `Files changed` tab, browsed repository in branch
- [x] Documentation updated - reflects changes in code, electrical or mechanical design
- [x] Documentation and graphics follow the [documentation style guide](https://github.com/RespiraWorks/Ventilator/wiki/Documentation-style-guide)
- [x] New content is linked, easily discoverable, does not require too many clicks
- [x] Follows other relevant parts of [contributor wiki](https://github.com/RespiraWorks/Ventilator/wiki)
- [x] PR has a descriptive name
- [x] Tagged relevant reviewers

### Software only:

- [x] Follows our [code style](https://github.com/RespiraWorks/Ventilator/wiki/Code-style)
- [x] Commented code, particularly in hard-to-understand areas
- [ ] All tests pass - new and old, locally and on CI (a dead link in an unrelated part of the repo)
- [x] No new warnings or static check failures
- [x] Tests that prove fix is effective or new feature works
- [x] Manual tests are explained, with instructions for reproducing them

2022-07-20 05:05 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RespiraWorks/Ventilator?pullRequest=1290) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RespiraWorks/Ventilator?pullRequest=1290) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RespiraWorks/Ventilator?pullRequest=1290) it.</sub>

2022-07-21 08:20 UTC, martukas requested changes
The 2 implemented functions work:
```
[port:/dev/ttyACM0] set blower_cal lin(0, 0.8)
[port:/dev/ttyACM0] get blower_cal
w+ blower_cal                     = [0.000 0.080 0.160 0.240 0.320 0.400 0.480 0.560 0.640 0.720 0.800] 
[port:/dev/ttyACM0] set blower_cal eigen()
[port:/dev/ttyACM0] get blower_cal
w+ blower_cal                     = [0.000 0.100 0.200 0.300 0.400 0.500 0.600 0.700 0.800 0.900 1.000] 
```
Assignment of simple arithmetic to float variables also works:
```
[port:/dev/ttyACM0] get blower_valve_kd
w+ blower_valve_kd                =                     0.000 
[port:/dev/ttyACM0] set blower_valve_kd 0.5*0.5
[port:/dev/ttyACM0] get blower_valve_kd
w+ blower_valve_kd                =                     0.250 
```

However, a number of edge cases with incorrect input generate rather unhelpful-to-the-end-user stack dumps:
```
[port:/dev/ttyACM0] set blower_cal lin()
Traceback (most recent call last):
  File "/home/martin/ventilator/software/utils/debug/./debug_cli.py", line 138, in cli_loop
    return cmd.Cmd.cmdloop(self)
  File "/usr/lib/python3.10/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python3.10/cmd.py", line 217, in onecmd
    return func(arg)
  File "/home/martin/ventilator/software/utils/debug/./debug_cli.py", line 611, in do_set
    self.interface.variable_set(args.var, data)
  File "/home/martin/ventilator/software/utils/debug/controller_debug.py", line 306, in variable_set
    data = variable.to_bytes(eval(f"{value}"))
  File "<string>", line 1, in <module>
TypeError: DebugFunctions.lin() missing 2 required positional arguments: 'a' and 'b'
[port:/dev/ttyACM0] set blower_cal "abcdefghi"
Traceback (most recent call last):
  File "/home/martin/ventilator/software/utils/debug/./debug_cli.py", line 138, in cli_loop
    return cmd.Cmd.cmdloop(self)
  File "/usr/lib/python3.10/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python3.10/cmd.py", line 217, in onecmd
    return func(arg)
  File "/home/martin/ventilator/software/utils/debug/./debug_cli.py", line 611, in do_set
    self.interface.variable_set(args.var, data)
  File "/home/martin/ventilator/software/utils/debug/controller_debug.py", line 306, in variable_set
    data = variable.to_bytes(eval(f"{value}"))
  File "/home/martin/ventilator/software/utils/debug/var_info.py", line 182, in to_bytes
    float_array = [float(k) for k in value]
  File "/home/martin/ventilator/software/utils/debug/var_info.py", line 182, in <listcomp>
    float_array = [float(k) for k in value]
ValueError: could not convert string to float: 'a'
[port:/dev/ttyACM0] set blower_cal 3
Traceback (most recent call last):
  File "/home/martin/ventilator/software/utils/debug/./debug_cli.py", line 138, in cli_loop
    return cmd.Cmd.cmdloop(self)
  File "/usr/lib/python3.10/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python3.10/cmd.py", line 217, in onecmd
    return func(arg)
  File "/home/martin/ventilator/software/utils/debug/./debug_cli.py", line 611, in do_set
    self.interface.variable_set(args.var, data)
  File "/home/martin/ventilator/software/utils/debug/controller_debug.py", line 306, in variable_set
    data = variable.to_bytes(eval(f"{value}"))
  File "/home/martin/ventilator/software/utils/debug/var_info.py", line 182, in to_bytes
    float_array = [float(k) for k in value]
TypeError: 'int' object is not iterable
[port:/dev/ttyACM0] set blower_valve_kd "abcd"
Traceback (most recent call last):
  File "/home/martin/ventilator/software/utils/debug/./debug_cli.py", line 138, in cli_loop
    return cmd.Cmd.cmdloop(self)
  File "/usr/lib/python3.10/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python3.10/cmd.py", line 217, in onecmd
    return func(arg)
  File "/home/martin/ventilator/software/utils/debug/./debug_cli.py", line 611, in do_set
    self.interface.variable_set(args.var, data)
  File "/home/martin/ventilator/software/utils/debug/controller_debug.py", line 306, in variable_set
    data = variable.to_bytes(eval(f"{value}"))
  File "/home/martin/ventilator/software/utils/debug/var_info.py", line 180, in to_bytes
    return debug_types.float32s_to_bytes(float(value))
ValueError: could not convert string to float: 'abcd'
[port:/dev/ttyACM0] set blower_valve_kd lin(0, 0.5)
Traceback (most recent call last):
  File "/home/martin/ventilator/software/utils/debug/./debug_cli.py", line 138, in cli_loop
    return cmd.Cmd.cmdloop(self)
  File "/usr/lib/python3.10/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python3.10/cmd.py", line 217, in onecmd
    return func(arg)
  File "/home/martin/ventilator/software/utils/debug/./debug_cli.py", line 611, in do_set
    self.interface.variable_set(args.var, data)
  File "/home/martin/ventilator/software/utils/debug/controller_debug.py", line 306, in variable_set
    data = variable.to_bytes(eval(f"{value}"))
  File "/home/martin/ventilator/software/utils/debug/var_info.py", line 180, in to_bytes
    return debug_types.float32s_to_bytes(float(value))
TypeError: float() argument must be a string or a real number, not 'list'
```

Also, trying to do any kind of composition with the array functions does not work:
```
[port:/dev/ttyACM0] set blower_cal eigen()*0.5
Traceback (most recent call last):
  File "/home/martin/ventilator/software/utils/debug/./debug_cli.py", line 138, in cli_loop
    return cmd.Cmd.cmdloop(self)
  File "/usr/lib/python3.10/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python3.10/cmd.py", line 217, in onecmd
    return func(arg)
  File "/home/martin/ventilator/software/utils/debug/./debug_cli.py", line 611, in do_set
    self.interface.variable_set(args.var, data)
  File "/home/martin/ventilator/software/utils/debug/controller_debug.py", line 306, in variable_set
    data = variable.to_bytes(eval(f"{value}"))
  File "<string>", line 1, in <module>
TypeError: can't multiply sequence by non-int of type 'float'
[port:/dev/ttyACM0] set blower_cal eigen().reverse()
Traceback (most recent call last):
  File "/home/martin/ventilator/software/utils/debug/./debug_cli.py", line 138, in cli_loop
    return cmd.Cmd.cmdloop(self)
  File "/usr/lib/python3.10/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python3.10/cmd.py", line 217, in onecmd
    return func(arg)
  File "/home/martin/ventilator/software/utils/debug/./debug_cli.py", line 611, in do_set
    self.interface.variable_set(args.var, data)
  File "/home/martin/ventilator/software/utils/debug/controller_debug.py", line 306, in variable_set
    data = variable.to_bytes(eval(f"{value}"))
  File "/home/martin/ventilator/software/utils/debug/var_info.py", line 182, in to_bytes
    float_array = [float(k) for k in value]
TypeError: 'NoneType' object is not iterable
```
This is likely (in part) because the custom functions are not generating generic float arrays.

Also, printing calibrations values with `get` does not provide information on whether a function is linear, etc.., which was discussed as a need in the original ticket.

I have pointed out some specific areas of code that may help solve some of the above edge case problems. You should have a very clear idea of which layer of the software which conversions and which error checks should be taking place. If it's hard to do off the cuff, maybe add some inline documentation defining inputs and outputs, assumptions about pre- and post-conditions for the various functions being modified. Please also note that the main CLI loop catches any Error-type exceptions and prints them in red.

I know that the handling of some of the above illustrated cases was not explicitly part of the ticket. However, the added functionalities touch heavily upon modules that are likely to have the end-user provoke these types of errors. So it seems to me a good time to also fundamentally improve those parts of the code to be of a better quality than they were b [...]

2022-07-21 16:01 UTC, a-vinod commented on software/utils/debug/debug_cli.py
> +            data = f"DebugFunctions.{''.join(args.data)}"
Good point! It seems eval() executes the expression in its argument in the same scope as the eval() itself, so this logic is redundant

2022-08-04 05:45 UTC, a-vinod commented
Many changes since Martin's review!
1. `data` in `set var data` can take any native Python or numpy data type, including functions and operations.
E.g.: `set psol_cal lin(1,5)*1.6+7`
2. Stack traces are not printed due to an error caused by evaluation of `data`
3. linearity of floatarrays are shown besides the data in `get`.
4. Better separation of functionality in between layers. E.g., eval() is only called in the CLI layer and types are checked at the variable `VarInfo` level
5. A helper function, `scoped_eval()`, in the `debug_funcs` module helps add our in-house functions and numpy functions to the scope of the `eval()` used to evaluate `data` without manually applying namespaces

2022-08-05 09:02 UTC, martukas requested changes
This looks good all in all - implementation-wise everything is layered well and manual testing was a satisfactory experience. Good job on figuring out the tolerance problem!

I am still requesting a few small changes just to make the code a bit cleaner. Since you don't have a fully functioning unit to test with, I it would be good to do one more review round just to make sure nothing gets accidentally broken.

2022-08-06 07:39 UTC, a-vinod commented on software/utils/debug/debug_cli.py
> +            properties = []
Good point! Property analysis is refactored out of this function now

2022-08-06 07:40 UTC, a-vinod commented on software/utils/debug/debug_cli.py
> +            if VAR_TYPE_REPRESENTATION[variable_md.type] == "A":
Ah you're right, I missed that for some reason. I used the constant instead now.

2022-08-06 07:40 UTC, a-vinod commented on software/utils/debug/debug_cli.py
> +            if isinstance(data, np.ndarray):
Commented!

2022-08-06 07:40 UTC, a-vinod commented on software/utils/debug/debug_cli.py
> +        # TODO: plotting (-p/--plot)?
Updated this comment as well

2022-08-06 08:01 UTC, a-vinod commented on software/utils/debug/debug_cli.py
> +            print(
It makes sense to me to try to predict common user errors. Namely:
1. variable is set to data of unexpected type (TypeError)
2. supported function incorrectly used (TypeError)
3. unsupported function used (NameError)

There can also be a catch-all `except Exception` after we check for TypeError and NameError for anything else we miss for now.

2022-08-06 08:04 UTC, a-vinod commented
TODO next day or so: testing every case of `set var` to make sure no existing or new functionality is broken

2022-08-06 22:15 UTC, a-vinod commented
Tested the `get` and `set` commands manually:
```
====================================================================
GET
====================================================================
[port:/dev/ttyACM0] get all
w- 0_controller_branch            = issue_1277_deploy_with_graphics 
w- 0_controller_build_time        =   UTC 2022-07-10 19:33:44 
w- 0_controller_git_dirty         =                         0 bool
w- 0_controller_pio_env           =                     STM32 
w- 0_controller_version           = 441a2701fa01d32f27af94ce61294b2b1be2f87e 
w+ 0_ventilator_serial_number     =                         0 
w- air_influx_dp                  =                     0.000 cmH2O
w- air_influx_flow                =                     0.000 mL/s
w- air_influx_voltage             =                     0.000 V
w- air_influx_zero                =                     0.000 V
w- bd_fast_flow_avg               =                     0.000 mL/s
w+ bd_fast_flow_avg_alpha         =                     0.200 
w+ bd_flow_trigger                =                   200.000 mL/s
w- bd_slow_flow_avg               =                     0.000 mL/s
w+ bd_slow_flow_avg_alpha         =                     0.010 
w+ blower_cal                     = [0.000 0.100 0.200 0.300 0.400 0.500 0.600 0.700 0.800 0.900 1.000] linear
w+ blower_valve_cal               = [0.000 0.041 0.069 0.099 0.127 0.159 0.193 0.236 0.294 0.399 1.000] 
w+ blower_valve_kd                =                     0.000 
w+ blower_valve_ki                =                    10.000 
w+ blower_valve_kp                =                     0.040 
w- breath_id                      =                         0 
w+ buzzer_cal                     = [0.000 0.080 0.160 0.240 0.320 0.400 0.480 0.560 0.640 0.720 0.800] linear
w+ exhale_valve_cal               = [0.000 0.041 0.069 0.099 0.127 0.159 0.193 0.236 0.294 0.399 1.000] 
w- fio2_fio2                      =                     0.000 ratio
w+ fio2_kd                        =                     0.000 
w+ fio2_ki                        =                     0.100 
w+ fio2_kp                        =                     0.001 
w- fio2_setpoint                  =                     0.210 ratio
w- fio2_voltage                   =                     0.000 V
w- fio2_zero                      =                     0.000 V
w- flow_correction                =                     0.000 mL/s
w+ forced_blower_power            =                    -1.000 ratio
w+ forced_blower_valve_position   =                    -1.000 ratio
w+ forced_breath_rate             =                        15 breaths/min
w+ forced_buzzer_volume           =                    -1.000 ratio
w+ forced_exhale_valve_position   =                    -1.000 ratio
w+ forced_fio2                    =                    21.000 %
w+ forced_ie_ratio                =                     0.660 ratio
w+ forced_mode                    =                   invalid 
w+ forced_peep                    =                         5 cmH2O
w+ forced_pip                     =                        15 cmH2O
w+ forced_psol_position           =                    -1.000 ratio
w- loop_latency                   =                      0.00 µs
w- loop_period                    =                     10000 µs
w- loop_time                      =                      0.00 µs
w- max_latency                    =                      0.00 µs
w- net_flow                       =                     0.000 mL/s
w- net_flow_uncorrected           =                     0.000 mL/s
w- nvparams_address               =                 536870936 
w+ nvparams_reinit                =                         0 
w- outflow_dp                     =                     0.000 cmH2O
w- outflow_flow                   =                     0.000 mL/s
w- outflow_voltage                =                     0.000 V
w- outflow_zero                   =                     0.000 V
w- oxygen_influx_dp               =                     0.000 cmH2O
w- oxygen_influx_flow             =                     0.000 mL/s
w- oxygen_influx_voltage          =                     0.000 V
w- oxygen_influx_zero             =                     0.000 V
w+ pa_min_expire_ms               =                   250.000 ms
w- patient_pressure_dp            =                     0.000 cmH2O
w- patient_pressure_voltage       =                     0.000 V
w- patient_pressure_zero          =                     0.000 V
w- pc_setpoint                    =                     0.000 cmH2O
w+ psol_cal                       = [0.350 0.390 0.430 0.470 0.510 0.550 0.590 0.630 0.670 0.710 0.750] linear
w+ psol_kd                        =                     0.000 
w+ psol_ki                        =                    20.000 
w+ psol_kp                        =                     0.040 
w- uncorrected_volume             =                     0.000 mL
w- volume                         =                     0.000 mL

[port:/dev/ttyACM0] get set
0_ventilator_serial_number     =                         0 
bd_fast_flow_avg_alpha         =                     0.200 
bd_flow_trigger                =                   200.000 mL/s
bd_slow_flow_avg_alpha         =                     0.010 
blower_cal                     = [0.000 0.100 0.200 0.300 0.400 0.500 0.600 0.700 0.800 0.900 1.000] linear
blower_valve_cal               = [0.000 0.041 0.069 0.099 0.127 0.159 0.193 0.236 0.294 0.399 1.000] 
blower_valve_kd                =                     0.000 
blower_valve_ki                =                    10.000 
blower_valve_kp                =                     0.040 
buzzer_cal                     = [0.000 0.080 0.160 0.240 0.320 0.400 0.480 0.560 0.640 0.720 0.800] linear
exhale_valve_cal               = [0.000 0.041 0.069 0.099 0.127 0.159 0.193 0.236 0.294 0.399 1.000] 
fio2_kd                        =                     0.000 
fio2_ki                        =                     0.100 
fio2_kp                        =                     0.001 
forced_blower_power            =                    -1.000 ratio
forced_blower_valve_position   =                    -1.000 ratio
forced_breath_rate             =                        15 breaths/min
forced_buzzer_volume           =                    -1.000 ratio
forced_exhale_valve_position   =                    -1.000 ratio
forced_fio2                    =                    21.000 %
forced_ie_ratio                =                     0.660 ratio
forced_mode                    =                   invalid 
forced_peep                    =                         5 cmH2O
forced_pip                     =                        15 cmH2O
forced_psol_position           =                    -1.000 ratio
nvparams_reinit                =                         0 
pa_min_expire_ms               =                   250.000 ms
psol_cal                       = [0.350 0.390 0.430 0.470 0.510 0.550 0.590 0.630 0.670 0.710 0.750] linear
psol_kd                        =                     0.000 
psol_ki                        =                    20.000 
psol_kp                        =                     0.040 

[port:/dev/ttyACM0] get read
0_controller_branch            = issue_1277_deploy_with_graphics 
0_controller_build_time        =   UTC 2022-07-10 19:33:44 
0_controller_git_dirty         =                         0 bool
0_controller_pio_env           =                     STM32 
0_controller_version           = 441a2701fa01d32f27af94ce61294b2b1be2f87e 
air_influx_dp                  =                     0.000 cmH2O
air_influx_flow                =                     0.000 mL/s
air_influx_voltage             =                     0.000 V
air_influx_zero                =                     0.000 V
bd_fast_flow_avg               =                     0.000 mL/s
bd_slow_flow_avg               =                     0.000 mL/s
breath_id                      =                         0 
fio2_fio2                      =                     0.000 ratio [...]

2022-08-07 01:10 UTC, a-vinod commented
Added some rudimentary unit testing too! It automates verifying the values before it's sent to lower-level layers to be processed into bytes and to the controller.

2022-08-08 11:45 UTC, martukas approved these changes
This looks really good now! While testing, I have found intermittent debug comms failures, but it is occurring in `master` as well, so I am quite sure that these code changes have no bearing on it.

2022-08-09 04:44 UTC, merged