Improve controller test coverage with test of pressure control laws
RespiraWorks/Ventilator pull request #881
Opened 2020-08-26 19:57 UTC by asmodai27

Adds simple test cases for the control laws, and the framework to add more complex cases, if we ever need to.

2020-09-10 14:36 UTC, martukas requested changes
I think some things could be done to improve readability.

I see the vision here, I guess this should serve as a basis for even more tests with other variations in parameters?

I could also ask -- can this be used to replay sequences of old recorded data to make sure the closed loop control still behaves "the same" as for when data was recorded with a lung?

Also, don't mean to be too demanding, but maybe the static checks (clnag, cppcheck) inspired any improvements in related code? Would be good to slowly start cleaning parts of code we touch so eventually we could enforce it on CI without provoking panic?

2020-09-10 20:49 UTC, asmodai27 reviewed
> I see the vision here, I guess this should serve as a basis for even more tests with other variations in parameters?
> I could also ask -- can this be used to replay sequences of old recorded data to make sure the closed loop control still behaves "the same" as for when data was recorded with a lung?

Absolutely, we could get the recorded data into a file (h file for example, like we did for breath detection in blower_fsm tests) and make this a very powerful test, once the controller gains and control laws are fully settled.

>Also, don't mean to be too demanding, but maybe the static checks (clnag, cppcheck) inspired any improvements in related code? Would be good to slowly start cleaning parts of code we touch so eventually we could enforce it on CI without provoking panic?

I did look at them, but they don't make sense to me...
The if/switch with identical branches in controller and sensors look like the branches are really different.
As for the "use '= default' to define a trivial constructor" in controller, I fail to see how this is a trivial constructor, since it takes parameters to initialize member values.

2020-09-10 20:49 UTC, asmodai27 commented on software/controller/test/controller/controller_test.cpp
> +  SensorReadings last_readings = {
SensorReadings is not a nanopb generated struct and there is therefore no predefined init_zero for this struct, I had to build it from scratch (and though I may have missed it, I don't see any other place where this is used).

2020-09-10 20:49 UTC, asmodai27 commented on software/controller/test/controller/controller_test.cpp
> +      (void)c.Run(Hal.now(), last_params, last_readings);
Sure

2020-09-10 20:49 UTC, asmodai27 commented on software/controller/test/controller/controller_test.cpp
> +      .fio2 = 0.21f,
Indeed

2020-09-10 20:49 UTC, asmodai27 commented on software/controller/test/controller/controller_test.cpp
> +      .patient_pressure = cmH2O(-500),
"pressure << Setpoint", since basically I want this to not depend on controller gains... will document better

2020-09-10 20:50 UTC, asmodai27 commented
I take back my statement about the default constructor, will update this as well.

2020-09-12 16:16 UTC, martukas approved these changes
LGTM

2020-09-12 16:57 UTC, merged